language: node_js
node_js:
  - "node"

install: yarn
cache:
  directories:
    - "node_modules"

script: yarn deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master