language: node_js
node_js:
  - "node"

install: yarn
cache:
  directories:
    - "node_modules"

script: yarn deploy

before_deploy:
  - rm -rf src
  - rm webpack.production.config.js webpack.config.js yarn.lock .eslintrc .babelrc
  - mv dist/* .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master